"""add_script_template_alert_rule_tables

Revision ID: a918a6a3f1c8
Revises: 2221cd4b9c4b
Create Date: 2026-05-04 00:45:31.506875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a918a6a3f1c8"
down_revision: str | None = "2221cd4b9c4b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_log",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_log", schema=None) as batch_op:
        batch_op.create_index("ix_alert_log_created", ["created_at"], unique=False)
        batch_op.create_index("ix_alert_log_session", ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_log_session_id"), ["session_id"], unique=False)

    op.create_table(
        "alert_rule",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column(
            "category",
            sa.Enum("COMPLIANCE", "EMOTION", "SILENCE", "PROCESS", name="alert_rule_category", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum("INFO", "WARNING", "CRITICAL", name="alert_rule_level", create_constraint=True),
            nullable=False,
        ),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="script_status", create_constraint=True), nullable=False
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_rule", schema=None) as batch_op:
        batch_op.create_index("ix_alert_rule_category_status", ["category", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_rule_rule_id"), ["rule_id"], unique=True)

    op.create_table(
        "script_template",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("script_id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("variables", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="script_status", create_constraint=True), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("script_template", schema=None) as batch_op:
        batch_op.create_index("ix_script_template_category", ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_template_script_id"), ["script_id"], unique=True)
        batch_op.create_index("ix_script_template_status_priority", ["status", "priority"], unique=False)

    op.create_table(
        "script_usage_log",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("script_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=False),
        sa.Column("pushed", sa.Boolean(), nullable=False),
        sa.Column("clicked", sa.Boolean(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("script_usage_log", schema=None) as batch_op:
        batch_op.create_index("ix_script_usage_log_created", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_script_usage_log_script_id"), ["script_id"], unique=False)
        batch_op.create_index("ix_script_usage_log_session", ["session_id"], unique=False)

    with op.batch_alter_table("kb_ingestion_log", schema=None) as batch_op:
        batch_op.alter_column(
            "step_detail_json",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.JSON(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kb_ingestion_log", schema=None) as batch_op:
        batch_op.alter_column(
            "step_detail_json",
            existing_type=sa.JSON(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            existing_nullable=True,
        )

    with op.batch_alter_table("script_usage_log", schema=None) as batch_op:
        batch_op.drop_index("ix_script_usage_log_session")
        batch_op.drop_index(batch_op.f("ix_script_usage_log_script_id"))
        batch_op.drop_index("ix_script_usage_log_created")

    op.drop_table("script_usage_log")
    with op.batch_alter_table("script_template", schema=None) as batch_op:
        batch_op.drop_index("ix_script_template_status_priority")
        batch_op.drop_index(batch_op.f("ix_script_template_script_id"))
        batch_op.drop_index("ix_script_template_category")

    op.drop_table("script_template")
    with op.batch_alter_table("alert_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_rule_rule_id"))
        batch_op.drop_index("ix_alert_rule_category_status")

    op.drop_table("alert_rule")
    with op.batch_alter_table("alert_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_log_session_id"))
        batch_op.drop_index("ix_alert_log_session")
        batch_op.drop_index("ix_alert_log_created")

    op.drop_table("alert_log")
    # ### end Alembic commands ###
